services:
    
  node:
    restart: always
    container_name: mongo_test
    environment:
      NODE_NUMBER: 1
    ports:
      - '47520:3000'
    build:
      context: .
      dockerfile: ./Dockerfile.node
    depends_on:
      mongo:
        condition: service_healthy
        restart: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - database_volume:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  database_volume:


    
