# build using $ docker build -t <image_name>
# run using   $ docker run <image_name>

FROM node:22-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app/

#copy over package.json and install necessary packages
COPY ./package.json /usr/src/app/
RUN npm install

#copy over the rest of the code into the container
COPY . /usr/src/app/

#start our node
CMD ["node", "index.js"]